name: Test secrets
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    environment: env
    steps:
      - name: Print secret
        run: echo "A senha é ${{ secrets.SECRET }}"
      - uses: actions/checkout@v4
      - name: listar diretorio
        run: ls -la
        
  clone-manual:
    runs-on: ubuntu-latest
    steps:
      - name: Configurar Git
        run: git --version  # só para mostrar que o git já existe
  
      - name: Clonar repositório manualmente
        run: |
          git clone https://github.com/${{ github.repository }} .
