name: Test secrets
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    environment: env
    steps:
      - name: Print secret
        run: echo "A senha é ${{ secrets.SECRET }}"
      - name: listar diretorio
        run: ls - la
