name: Test secrets
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    environment: env
    steps:
      - name: Print secret
        run: echo "A senha é ${{ secrets.SECRET }}"
      - uses: actions/checkout@v4
      - name: listar diretorio
        run: ls -la
        
  clone-manual:
    runs-on: ubuntu-latest
    steps:
      - name: Configurar Git
        run: git --version  # só para mostrar que o git já existe
  
      - name: Clonar repositório manualmente
        run: git clone https://github.com/${{ github.repository }} .
      - name: listar diretorio
        run: ls -la
        
  node-job:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v4
      - name: Usar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'   # versão que você quiser: 16, 18, 20, etc

      - name: Checar versão do Node
        run: node --version
        
      - name: Verificar arquivos no diretório
        run: ls -la

      - name: Rodar um arquivo JavaScript
        run: node sum.test.js
