name: Test secrets
on: [push]
jobs:
        
  clone-manual:
    runs-on: ubuntu-latest
    steps:
      - name: Configurar Git
        run: git --version  # só para mostrar que o git já existe
  
      - name: Clonar repositório manualmente
        run: |
          git clone https://github.com/${{ github.repository }} .
